import { StyleSheet } from "react-native";
import { colors, sizes } from "@utils";

export const notasStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background || "#f9f9f9",
    padding: 0,
  },
  title: {
    fontSize: sizes.lg || 22,
    fontWeight: "bold",
    marginBottom: sizes.base || 15,
    color: colors.primary || "#1e3a8a",
    textAlign: "center",
  },
  composerCard: {
    backgroundColor: colors.surface || "#fff",
    borderRadius: sizes.radius || 12,
    borderWidth: 1,
    borderColor: colors.border || "#ddd",
    padding: sizes.sm || 10,
    marginBottom: sizes.sm || 12,
  },
  titleInput: {
    backgroundColor: colors.surface || "#fff",
    padding: sizes.sm || 10,
    borderRadius: sizes.radius || 10,
    borderWidth: 1,
    borderColor: colors.border || "#ccc",
    marginBottom: sizes.sm || 10,
    fontWeight: "600",
  },
  composerRow: { flexDirection: "row", alignItems: "flex-start" },
  input: {
    flex: 1,
    backgroundColor: colors.surface || "#fff",
    padding: sizes.sm || 10,
    borderRadius: sizes.radius || 10,
    borderWidth: 1,
    borderColor: colors.border || "#ccc",
    minHeight: 44,
    textAlignVertical: "top",
  },
  addButton: {
    backgroundColor: colors.primary || "#27282cff",
    paddingVertical: sizes.sm || 10,
    paddingHorizontal: sizes.base || 15,
    borderRadius: sizes.radius || 10,
    marginLeft: sizes.sm || 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  addButtonText: {
    color: colors.onPrimary || "#fff",
    fontWeight: "bold",
    marginLeft: 6,
  },
  composerActions: { flexDirection: "row", marginTop: sizes.sm || 8 },
  previewContainer: { marginBottom: sizes.sm || 10, alignItems: "center" },
  previewImage: {
    width: "100%",
    borderRadius: sizes.radius || 12,
    backgroundColor: "#00000010",
  },
  previewRemove: {
    position: "absolute",
    right: 10,
    top: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  previewRemoveText: { color: "#fff", marginLeft: 4, fontSize: 12 },
  notesList: { marginTop: 0 },
  notesListContent: { paddingBottom: 0, flexGrow: 1 },
  noteCard: {
    backgroundColor: colors.surface || "#fff",
    padding: sizes.base || 15,
    borderRadius: sizes.radius || 10,
    marginBottom: sizes.sm || 10,
    borderWidth: 1,
    borderColor: colors.border || "#ddd",
  },
  noteCardEditing: {
    borderColor: colors.primary || "#27282cff",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  noteHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  noteMenuButton: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    marginLeft: 8,
    borderRadius: 8,
  },
  noteImage: {
    width: "100%",
    borderRadius: sizes.radius || 10,
    marginBottom: sizes.sm || 8,
    backgroundColor: "#00000010",
  },
  noteImagePlaceholder: {
    width: "100%",
    height: 160,
    borderRadius: sizes.radius || 10,
    marginBottom: sizes.sm || 8,
    borderWidth: 1,
    borderColor: colors.border || "#ddd",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fafafa",
  },
  placeholderText: { opacity: 0.6, fontSize: 12 },
  noteTitle: {
    fontSize: sizes.md || 18,
    fontWeight: "bold",
    color: colors.textPrimary || "#1e1f20",
  },
  noteText: {
    fontSize: sizes.sm || 15,
    color: colors.textSecondary || "#444",
    marginBottom: 8,
    lineHeight: 20,
  },
  noteDate: {
    fontSize: 12,
    opacity: 0.6,
    marginTop: sizes.xs || 4,
  },
  noteReminder: {
    fontSize: 12,
    marginTop: 4,
    color: colors.primary || "#1e3a8a",
  },
  emptyText: {
    textAlign: "center",
    opacity: 0.6,
    marginTop: sizes.base || 20,
  },
  cardActions: {
    flexDirection: "row",
    marginTop: sizes.sm || 8,
    flexWrap: "wrap",
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: sizes.base || 14,
    marginTop: 6,
  },
  actionText: { marginLeft: 6, fontSize: 13, opacity: 0.9 },
  editTitleInput: {
    borderWidth: 1,
    borderColor: colors.border || "#ddd",
    borderRadius: sizes.radius || 8,
    padding: sizes.sm || 8,
    marginTop: sizes.xs || 6,
    fontWeight: "600",
  },
  editInput: {
    borderWidth: 1,
    borderColor: colors.border || "#ddd",
    borderRadius: sizes.radius || 8,
    padding: sizes.sm || 8,
    minHeight: 40,
    marginTop: sizes.xs || 6,
    textAlignVertical: "top",
  },
  authRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: sizes.base || 20,
  },
  authBtn: {
    flex: 1,
    minWidth: 0,
  },
  mr8: { marginRight: sizes.sm || 8 },

  reminderMenuOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 40,
  },
  reminderMenuCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 22,
    width: "82%",
    maxWidth: 360,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 16,
    alignItems: "center",
  },
  reminderMenuIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  reminderMenuIconCircleReminder: {
    backgroundColor: "#667eea",
  },
  reminderMenuIconCircleEdit: {
    backgroundColor: "#f5576c",
  },
  reminderMenuIconCircleNotification: {
    backgroundColor: "#fcb69f",
  },
  reminderMenuIconEmoji: {
    fontSize: 30,
    color: "#ffffff",
  },
  reminderMenuTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: "#2c3e50",
    textAlign: "center",
    marginBottom: 8,
  },
  reminderMenuText: {
    fontSize: 14,
    color: "#6c757d",
    textAlign: "center",
    marginBottom: 14,
  },

  reminderStepsContainer: {
    width: "100%",
    marginBottom: 14,
  },
  reminderStep: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#28a745",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  reminderStepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#28a745",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 2,
  },
  reminderStepNumber: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 16,
  },
  reminderStepContent: {
    flex: 1,
  },
  reminderStepTitle: {
    fontWeight: "600",
    fontSize: 14,
    color: "#2c3e50",
    marginBottom: 2,
  },
  reminderStepDescription: {
    fontSize: 13,
    color: "#6c757d",
  },

  reminderMenuButtonsRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  reminderMenuButtonsRowSecondary: {
    width: "100%",
    marginTop: 10,
  },
  reminderMenuBtn: {
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  reminderMenuBtnPrimary: {
    flex: 1,
    marginRight: 6,
    backgroundColor: "#667eea",
  },
  reminderMenuBtnSecondary: {
    flex: 1,
    marginLeft: 6,
    backgroundColor: "#f8f9fa",
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  reminderMenuBtnDanger: {
    width: "100%",
    backgroundColor: "#ee5a52",
  },
  reminderMenuBtnText: {
    fontSize: 15,
    fontWeight: "600",
  },
  reminderMenuBtnTextPrimary: {
    color: "#ffffff",
  },
  reminderMenuBtnTextSecondary: {
    color: "#6c757d",
  },
  reminderMenuBtnTextDanger: {
    color: "#ffffff",
  },
});
