import { StyleSheet, Platform } from "react-native";

const BLUE = "#3B82F6";
const BLUE_DARK = "#1D4ED8";
const BG = "#0B0F14";
const CARD = "#0F172A";
const WHITE = "#FFFFFF";
const MUTED = "#9CA3AF";
const RING = "#2C3E8F";

export const qrStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: BG,
  },
  header: {
    paddingTop: Platform.select({ ios: 18, android: 8 }),
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: BG,
  },
  headerTitle: {
    color: WHITE,
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    marginTop: 4,
    color: MUTED,
    fontSize: 13,
  },
  cameraWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  camera: { ...StyleSheet.absoluteFillObject },
  overlay: {
    frameSize: 260,
    root: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
    },
    frame: {
      width: 260,
      height: 260,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: RING,
      backgroundColor: "rgba(15, 23, 42, 0.28)",
      overflow: "hidden",
    },
    corner: {
      position: "absolute",
      width: 38,
      height: 38,
      borderWidth: 4,
      borderColor: BLUE,
    },
    tl: { top: -2, left: -2, borderRightWidth: 0, borderBottomWidth: 0, borderTopLeftRadius: 16 },
    tr: { top: -2, right: -2, borderLeftWidth: 0, borderBottomWidth: 0, borderTopRightRadius: 16 },
    bl: { bottom: -2, left: -2, borderRightWidth: 0, borderTopWidth: 0, borderBottomLeftRadius: 16 },
    br: { bottom: -2, right: -2, borderLeftWidth: 0, borderTopWidth: 0, borderBottomRightRadius: 16 },
    scanLine: {
      position: "absolute",
      left: 0,
      right: 0,
      height: 2,
      backgroundColor: BLUE,
      opacity: 0.85,
    },
  } as any,
  resultCard: {
    marginHorizontal: 20,
    marginTop: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1F2937",
    backgroundColor: CARD,
    padding: 14,
    minHeight: 64,
    opacity: 0.6,
  },
  resultVisible: { opacity: 1 },
  statusText: { color: MUTED, fontSize: 13, textAlign: "center" },
  resultLabel: { color: MUTED, fontSize: 12, textTransform: "uppercase", letterSpacing: 0.6 },
  resultText: { color: WHITE, fontSize: 14, marginTop: 6 },
  actions: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    backgroundColor: BG,
  },
  hintText: { color: MUTED, fontSize: 12, textAlign: "center" },
  btnRow: { flexDirection: "row", gap: 12, marginBottom: 10 },
  primaryBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: BLUE,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  primaryBtnText: { color: WHITE, fontSize: 15, fontWeight: "700" },
  secondaryBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: BLUE,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  secondaryBtnText: { color: BLUE, fontSize: 15, fontWeight: "700" },
  ghostBtn: {
    marginTop: 6,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1F2937",
    backgroundColor: "rgba(15,23,42,0.6)",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  ghostBtnText: { color: WHITE, fontSize: 14, fontWeight: "600" },
  permTitle: { color: WHITE, fontSize: 16, marginBottom: 12, textAlign: "center" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    backgroundColor: CARD,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1F2937",
  },
  modalTitle: { color: WHITE, fontSize: 18, fontWeight: "700" },
  modalHint: { color: MUTED, fontSize: 12, marginTop: 10, marginBottom: 6 },
  modalInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#334155",
    paddingHorizontal: 12,
    color: WHITE,
    backgroundColor: "#0B1220",
  },
  modalLinkPreview: { color: MUTED, fontSize: 12, marginTop: 8 },
  modalRow: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 14 },
  modalCancel: {
    paddingHorizontal: 14,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#334155",
  },
  modalCancelText: { color: WHITE, fontSize: 14, fontWeight: "600" },
  modalSave: {
    paddingHorizontal: 14,
    height: 40,
    borderRadius: 10,
    backgroundColor: BLUE_DARK,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  modalSaveText: { color: WHITE, fontSize: 14, fontWeight: "700" },
});
